spring:
  application:
    name: bookingservice
  datasource:
    url:
    # username:
    # password:
  jpa:
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true
